/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocumentParsingRouteImport } from './routes/document-parsing'
import { Route as WikiRouteRouteImport } from './routes/wiki/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WikiIndexRouteImport } from './routes/wiki/index'
import { Route as AuthVerificationPendingRouteImport } from './routes/auth/verification-pending'
import { Route as AuthVerificationRouteImport } from './routes/auth/verification'
import { Route as AuthSignUpRouteImport } from './routes/auth/sign-up'
import { Route as AuthSignInRouteImport } from './routes/auth/sign-in'
import { Route as AuthGoogleCallbackRouteImport } from './routes/auth/google/callback'

const DocumentParsingRoute = DocumentParsingRouteImport.update({
  id: '/document-parsing',
  path: '/document-parsing',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiRouteRoute = WikiRouteRouteImport.update({
  id: '/wiki',
  path: '/wiki',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WikiIndexRoute = WikiIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WikiRouteRoute,
} as any)
const AuthVerificationPendingRoute = AuthVerificationPendingRouteImport.update({
  id: '/auth/verification-pending',
  path: '/auth/verification-pending',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthVerificationRoute = AuthVerificationRouteImport.update({
  id: '/auth/verification',
  path: '/auth/verification',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpRoute = AuthSignUpRouteImport.update({
  id: '/auth/sign-up',
  path: '/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignInRoute = AuthSignInRouteImport.update({
  id: '/auth/sign-in',
  path: '/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthGoogleCallbackRoute = AuthGoogleCallbackRouteImport.update({
  id: '/auth/google/callback',
  path: '/auth/google/callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/wiki': typeof WikiRouteRouteWithChildren
  '/document-parsing': typeof DocumentParsingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/auth/verification-pending': typeof AuthVerificationPendingRoute
  '/wiki/': typeof WikiIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/document-parsing': typeof DocumentParsingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/auth/verification-pending': typeof AuthVerificationPendingRoute
  '/wiki': typeof WikiIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/wiki': typeof WikiRouteRouteWithChildren
  '/document-parsing': typeof DocumentParsingRoute
  '/auth/sign-in': typeof AuthSignInRoute
  '/auth/sign-up': typeof AuthSignUpRoute
  '/auth/verification': typeof AuthVerificationRoute
  '/auth/verification-pending': typeof AuthVerificationPendingRoute
  '/wiki/': typeof WikiIndexRoute
  '/auth/google/callback': typeof AuthGoogleCallbackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/wiki'
    | '/document-parsing'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verification'
    | '/auth/verification-pending'
    | '/wiki/'
    | '/auth/google/callback'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/document-parsing'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verification'
    | '/auth/verification-pending'
    | '/wiki'
    | '/auth/google/callback'
  id:
    | '__root__'
    | '/'
    | '/wiki'
    | '/document-parsing'
    | '/auth/sign-in'
    | '/auth/sign-up'
    | '/auth/verification'
    | '/auth/verification-pending'
    | '/wiki/'
    | '/auth/google/callback'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  WikiRouteRoute: typeof WikiRouteRouteWithChildren
  DocumentParsingRoute: typeof DocumentParsingRoute
  AuthSignInRoute: typeof AuthSignInRoute
  AuthSignUpRoute: typeof AuthSignUpRoute
  AuthVerificationRoute: typeof AuthVerificationRoute
  AuthVerificationPendingRoute: typeof AuthVerificationPendingRoute
  AuthGoogleCallbackRoute: typeof AuthGoogleCallbackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/document-parsing': {
      id: '/document-parsing'
      path: '/document-parsing'
      fullPath: '/document-parsing'
      preLoaderRoute: typeof DocumentParsingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki': {
      id: '/wiki'
      path: '/wiki'
      fullPath: '/wiki'
      preLoaderRoute: typeof WikiRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wiki/': {
      id: '/wiki/'
      path: '/'
      fullPath: '/wiki/'
      preLoaderRoute: typeof WikiIndexRouteImport
      parentRoute: typeof WikiRouteRoute
    }
    '/auth/verification-pending': {
      id: '/auth/verification-pending'
      path: '/auth/verification-pending'
      fullPath: '/auth/verification-pending'
      preLoaderRoute: typeof AuthVerificationPendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/verification': {
      id: '/auth/verification'
      path: '/auth/verification'
      fullPath: '/auth/verification'
      preLoaderRoute: typeof AuthVerificationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-up': {
      id: '/auth/sign-up'
      path: '/auth/sign-up'
      fullPath: '/auth/sign-up'
      preLoaderRoute: typeof AuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/sign-in': {
      id: '/auth/sign-in'
      path: '/auth/sign-in'
      fullPath: '/auth/sign-in'
      preLoaderRoute: typeof AuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/google/callback': {
      id: '/auth/google/callback'
      path: '/auth/google/callback'
      fullPath: '/auth/google/callback'
      preLoaderRoute: typeof AuthGoogleCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface WikiRouteRouteChildren {
  WikiIndexRoute: typeof WikiIndexRoute
}

const WikiRouteRouteChildren: WikiRouteRouteChildren = {
  WikiIndexRoute: WikiIndexRoute,
}

const WikiRouteRouteWithChildren = WikiRouteRoute._addFileChildren(
  WikiRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  WikiRouteRoute: WikiRouteRouteWithChildren,
  DocumentParsingRoute: DocumentParsingRoute,
  AuthSignInRoute: AuthSignInRoute,
  AuthSignUpRoute: AuthSignUpRoute,
  AuthVerificationRoute: AuthVerificationRoute,
  AuthVerificationPendingRoute: AuthVerificationPendingRoute,
  AuthGoogleCallbackRoute: AuthGoogleCallbackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
